### PR TITLE
DAY 1 - React Insta Clone

### PR DESCRIPTION
**Pull request by WarVDine**
Goals for today:
- Basic JSX typed out
- Basic styling to match the 'instagram look'
- Checking PropTypes

### CODE REVIEW

**Comment by WarVDine** [comment]
Changelog for today:

MVP:
- Add comments
- Like posts
  + Update 'likes' counter
  + Heart turns red
  + Toggles, like++ or like--
- Search functionality
  + Shoutout to Omar for the filter coding

Stretch:
- localStorage
  + New comments needed to chain all the way up to App.js in order to localStorage.setItem properly
- delete Comments
  + Code is VERY convoluted here(sorry!)
  + Comment.js clicks to a delete function that takes the {comment} obj and calls =>
  + CommentSectionjs delete function. This takes the comment.id with the post.id and calls =>
  + Post.js => PostContainer.js =>
  + App.js deleteComment function. This checks for the proper post.id and the proper comment.id,
  + then splices the array to deleted the selected comment.
  + CANNOT delete the original user's comment(would cause errors for the Image alt tag)

Styling:
- <span>Delete</span> only appears when hovering over each specific comment
- Delete turns bluer when hovering
- <button>Post</button> turns bluer if there is a comment that can be posted. 
  + Backspace the whole comment, and the button will gray out again.
  + Style idea taken from Instagram.

**Comment by WarVDine** [comment]
Changelog for today:

MVP:
- Everything that once was App.js is now PostsPage.js
- HOC created 
  + Takes in <Login/> and <PostsPage/> 
  + Uses logic to determine which component to render
- Login page created
  + Username stored in localStorage for adding comments properly

Stretch:
- Added logout menu connected to the SearchBar
  + Click on the user icon, then click 'Log Out'
  + Removes 'username' from localStorage
- Deployed to Netlify
- Created a fake database of usernames. If user logs in with incorrect credentials, they will not be able to log in

**Comment by WarVDine** [comment]
Changelog:

MVP:
- Added Styled Components 100% except for icons
  + Changed some icon classes to differentiate between header icons and the icons within each post
- For .scss that still had slight icon styling, all other styles were commented out
- For .scss files that are now uneeded, the import on the corresponding .js file was commented out
  + Example: Login.scss has no sommented out code, but Login.js no longer imports the scss file

Stretch: 
- Created a Register Page.
  + Links to localStorage to add a user
  + To add a user:
    - All fields must be filled
    - Username must be 5 characters or more
    - Passwords must match
    - Username must not already be taken (try registering with the username "Sonic"
  + Once all fields are filled, button will light up and function properly
  + If there are any errors, error text will appear

**Comment by guillearria** [comment]
Exemplary commit history Devin, bravo... your employer and collaborative development partners are going to be blessed to have you on their team 👍

**Pull request merged**
